### ISSUE TITLE
Relationships not drawn

### ISSUE THREAD

**Issue by rweverwijk** [neo4j-apps/neo4j-bloom#1]
I've worked quite a lot with Neo4j Bloom lately. It works great. But there are some strange things happening. 

Relationships are not drawn consistently. I think I've found the minimal scenario to run into this issue.

* Run a pattern query.
  * Result is shown correctly. 
* select all (CMD + A)
* hide all (CMD + H)
* run same patthern
  * Nodes are shown, relationships not
* refresh the application (CMD + R)
  * Result is shown correctly

Versions:
Bloom: 1.0.1
Neo4j: 3.4.1 Enterprise
OS: OSX (Have the feeling that on Ubuntu there are more scenarios to run into this)

**Comment by tiansivive** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github - Relationships not drawn](https://trello.com/c/ycb7hkb3/1152-github-relationships-not-drawn)

**Comment by rweverwijk** [comment]
Hi @tiansivive good to see some action, although I cannot see the trello card on the private board.

If you need to have more info or a testrun, please give a shout!

**Comment by joknelid** [comment]
We have a fix for this and it should be going out with the next Bloom release

**Comment by rweverwijk** [comment]
Great, thanks! Is there a way I can help you testing it before the release?

**Comment by joknelid** [comment]
There are some loose plans to have some sort of beta channel in Neo4j Desktop but until then there isn't

**Comment by joknelid** [comment]
Fixed in Bloom 1.0.2, closing
