### ISSUE TITLE
Bolt connection on non-default port - different behavior between neo4j server and desktop

### ISSUE THREAD

**Issue by michela** [neo4j-apps/neo4j-bloom#10]
To avoid opening neo4j ports on firewall, I'm trying to use nginx to port forward port 80 traffic to neo4j. This works in browser but not in Desktop

ie.
project-neo4j.domain.com:80 to local neo4j server on 7474
project-bolt.domain.com:80 to local neo4j server on 7687

So I can then access browser via web server on

 http://project-neo4j.domain.com/browser/

once I've changed Connect URL to 
bolt://project-bolt.domain.com:80

(default port not accessible through firewall but this works)

HOWEVER in Bloom you get this error if you specify a different port 

>  ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3

Ideally what I'd like to do is configure the server so that the default settings specify my non-standard ports in the connection settings in the client WITHOUT changing the server's listening ports (which I haven't changed from the defaults).

**Comment by michela** [comment]
I should add that part of the reason for this is that I've got different neo4j servers behind the firewall so simply opening up the neo4j ports on the firewall doesn't scale in this instance.

**Comment by joknelid** [comment]
Hi! Thanks for reporting

Just so we can completely understand what you are trying to do, are you running Bloom from Neo4j Desktop, hosted by the Bloom Neo4j plugin or just self hosted web assets?

If it's Desktop, are you using a remote graph pointed to bolt://project-bolt.domain.com:80?
Is "use encrypted connection" checked or not?

**Comment by michela** [comment]
Yes running Bloom from Desktop with that url and encrypted connection checked. Will Test non encrypted and report back.

**Comment by joknelid** [comment]
Did you manage to get it working? Have you tested without encrypted connection?

**Comment by joknelid** [comment]
Closing b/c of inactivity
