### ISSUE TITLE
Bloom can get Double characters correctly?

### ISSUE THREAD

**Issue by sunparkmos** [neo4j-apps/neo4j-bloom#2]
I followed below northwind importing guide and the only difference is uploading "Korean" northwind CSV files.
https://neo4j.com/developer/guide-importing-data-and-etl/
Tutorial: Import Data Into Neo4j
From “Bloom getting started.pdf”,  I knew Bloom can get some data with [Beverages / Supplier of Product Beverages / Beverages Product Supplier / Employee with lastName Fuller / who reports to Fuller] as search words.
So I tried 음료, that is Korean Words of "Beverages", but failed.
1. I tried with 음료, and then changed from 음료 to ‘음료’, automatically, and the displayed bloom1.jpg
![bloom1](https://user-images.githubusercontent.com/26949497/45328922-ef585480-b598-11e8-8ac2-d455632cd1b5.jpg)

2. I tried with "음료", and then displayed bloom2.jpg
![bloom2](https://user-images.githubusercontent.com/26949497/45328931-f54e3580-b598-11e8-8111-59367da269cc.jpg)

3. I can see 음료 category correctly from Neo4j Browser. You can refer bloom3.jpg
![bloom3](https://user-images.githubusercontent.com/26949497/45328938-fbdcad00-b598-11e8-87d9-f8c839665bab.jpg)

4. I attached categories.zip with a categories.csv which was from Korean Microsoft Access.
[categories.zip](https://github.com/neo4j-apps/neo4j-bloom/files/2368700/categories.zip)

Please enlighten me what are wrong with my Bloom.

**Comment by joknelid** [comment]
Thanks for reporting! I could reproduce this in my environment so have created an internal ticket for tracking
