### ISSUE TITLE
Expanding Deep links by default

### ISSUE THREAD

**Issue by peterkva** [neo4j-apps/neo4j-bloom#21]
Submitting a deep link query to Bloom, is there a way to have the found node(s) appear totally expanded without user interaction (i.e. user does not have to hit return to see the resulting graph)?

**Comment by angeliquekom** [comment]
hi @peterkva. We have gotten this request before but we are a bit worried because of security reasons.

**Comment by peterkva** [comment]
Can you clarify a bit on what the security concerns are?
Also, does this mean that this feature is not planned to be implemented?

**Comment by angeliquekom** [comment]
The main security concern is that running any kind of cypher using a search phrase could lead to undesired effect on the database, like destroying data. Forcing return we have better control of the type of the queries defined by the users. Currently, we don't have this feature in our roadmap but we continuously check the popularity of the users issues and reconsider including them in future implementations.

**Comment by joknelid** [comment]
This has been possible since `1.5.1` by adding the query parameter `run=true`. Closing
