### ISSUE TITLE
"Import project from file" does not work

### ISSUE THREAD

**Issue by kixxalot** [neo4j-apps/neo4j-bloom#23]
"Import project from file" does not work: it results in a new project with .json files, not a new project with the perspectives and db already set up.

To reproduce:

1. Create some perspective in Bloom
2. "Experimental features" > "Export all perspectives"
3. Now try and import this .zip file in Bloom: CTRL+I

Result: in Neo Desktop a new project is added with .json file(s) - no way to open these as a Bloom perspective

Expected: perspective(s) added to Bloom  

Neo4J Desktop (WIndows) 1.3.11

**Comment by tbwiss** [comment]
Hej @kixxalot!
What you are trying to do is not supported or possible at this moment in Bloom and Neo4j Desktop.
If you wish to use the exported perspectives in a different db, connect Bloom to that db and import the perspectives (one by one) in the perspective gallery.

**Comment by kixxalot** [comment]
Thanks @tbwiss 

Closing this issue, as importing perspectives one by one does work.
