### ISSUE TITLE
WANT Bloom: edit "Rule Style" names

### ISSUE THREAD

**Issue by gitclem** [neo4j-apps/neo4j-bloom#24]
It's great you can create style rules in Bloom which changes what nodes look like.

But... you can't seem to change the name from "Rule Style N" to something more meaningful. Also clicking on the x to delete the Rule Style doesn't have a confirmation that you really want to do that... Maybe the icon should be a garbage can because you're deleting something.

**Comment by angeliquekom** [comment]
thanks @gitclem for your feedback. We'll take this into account for our next dev phase.

**Comment by angeliquekom** [comment]
hi @gitclem. In the latest Bloom release (v1.6.1) we set titles on each style rule depending on the configuration. Thanks for your feedback.

**Comment by joknelid** [comment]
Closing b/c of improvements in 1.6.1
