### ISSUE TITLE
Bloom Should use Shift-Click to make multiple selections

### ISSUE THREAD

**Issue by gitclem** [neo4j-apps/neo4j-bloom#26]
Bloom uses Command-Click (on the Mac) to make multiple selection of Nodes and Relationships.

For the Mac, it's standard to use Shift-Click.

**Comment by jharris4** [comment]
@gitclem Thanks for the feedback. Bloom's keyboard shortcuts are actually modelled after how things work in the MacOS Finder application. You'll notice that in Finder, Command-Click is used for multiple selection, whereas Shift-Click is used for selecting ranges. As such we don't have any plans to change from using Command-Click in the foreseeable future.
