### ISSUE TITLE
Case insensitive search & suggestions does not appear to work

### ISSUE THREAD

**Issue by kixxalot** [neo4j-apps/neo4j-bloom#31]
In settings there is an option "Case insensitive search & suggestions". With this option turned on, the suggestions in the search bar still are case sensitive. The name "John" is not shown as a suggestion when one types "joh". It is when one types "Joh".

Bloom 1.4.0 running on Linux.

**Comment by joknelid** [comment]
Hi!

Do you have full text indexes created for the properties you want to search (I guess name in your example)? The case insensitive search requires full text indexes for performance reasons

**Comment by kixxalot** [comment]
Hi, indeed I had not created full text indexes.  After creating full text indexes case insensitive search works, but the "full text search"  (i.e. not the auto-suggest) appears to be doing (very!) fuzzy rather than literal text searches. Is there a way to configure this so that the searches are not fuzzy, or to limit the fuzziness?

**Comment by joknelid** [comment]
Not really I'm afraid - the full text search is not configurable at the moment. If you want, you could go to our Canny page (via the "Help & Learn" sidebar drawer) and add a feature request. The more specific you can be about what you're trying to search and what you expect the more likely it is to be prioritised.

**Comment by kixxalot** [comment]
I'm closing this issue as creating full text indexes did enable case insensitive search & suggestions.
