### ISSUE TITLE
Layout will often not go back to "normal" after using hierarchical 

### ISSUE THREAD

**Issue by kixxalot** [neo4j-apps/neo4j-bloom#32]
To reproduce: make sure there is a nice number of nodes (say >200) on your screen. Then press the "hierarchical" layout button. Wait until the layout has changed. Then press the button again to go back to the "normal" layout.

Result: often the layout is now still (partially?) hierarchical.

**Comment by joknelid** [comment]
Is this with 1.4.0? Have you tried with the latest version? (Bloom 1.6.1) We have made a change so that it always resets the layout when the user switches between, so you shouldn't end up in some kind of in-between mode anymore

**Comment by kixxalot** [comment]
This is with 1.4 indeed, I will try the new version.

**Comment by kixxalot** [comment]
Indeed works much better in 1.6, closing this issue.
