### ISSUE TITLE
Expand nodes when zoomin in

### ISSUE THREAD

**Issue by moweigel** [neo4j-apps/neo4j-bloom#36]
I'm currently looking for an option to explore huge graphs more intuitive. I really like the visualization of Bloom and I thougt about the feature to automatically expand neigboured nodes and relations when zooming in (maybe while the mouse hovers over the desired node). Like an equivalent of zooming on a geographical map: the further u zoom in - the more detailes u receive of the specific area without the need to manually expanding a node. Is there any already excisting implementation that I missed? Else I would really appreciate a feature like that.

**Comment by joknelid** [comment]
Hi! Cool suggestion, there definitely isn't any feature like that. We will add it to our backlog so we can consider it for future releases 👍 

Also, if you want to give us more suggestions in the future can I ask you to use Canny? There is a big button in the "help & about" sidebar drawer (with the question mark icon)

**Comment by ckanz** [comment]
Thanks @moweigel for the great suggestion! I will be closing this issue since it's been some time since the last reply. If you have any more suggestions or issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore
