### ISSUE TITLE
Error Message when creating a Search Phrase

### ISSUE THREAD

**Issue by cdiniz** [neo4j-apps/neo4j-bloom#4]
If you create a search phrase without the query and you run it, you will get an "alert" message like this one: 

`AN ERROR OCCURRED WHILE EXECUTING SEARCH
Invalid input 'I': Expected 'o/O' (line 1, column 3 (offset: 2))
"LIMIT 10000"`

We know what this is about, but I think this should not happen. I see two options here, the search phrase couldn't be saved without a query, or the error should be explicit.

Version: Bloom 1.0.2, Neo4j Desktop 1.1.10

**Comment by joknelid** [comment]
Fixed in Bloom 1.0.3, closing
