### ISSUE TITLE
Size based rule is reversing result

### ISSUE THREAD

**Issue by andyhegedus** [neo4j-apps/neo4j-bloom#40]
I have a single node rule with default size 1x. I have refreshed the range and set it to a single integer property. I have added the property,"power" to the captions on the nodes.  The large numbers are appearing small and low values large. This is counter to the rule.
The Bloom version is 2.1.0
<img width="832" alt="image" src="https://user-images.githubusercontent.com/44418310/155361253-0ac0568b-5625-4f13-9f0c-88b5d18656b2.png">

Andy

**Comment by on5sl** [comment]
I have the same issue...also the color range rules don't work properly anymore.

**Comment by GlacialBoy** [comment]
Thanks for reporting, fixed with Bloom version 2.1.1

**Comment by ckanz** [comment]
I will be closing this issue since the bug has been fixed. Thanks again @on5sl for reporting it. If you have any other issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore
