### ISSUE TITLE
Separate URL for each search phrase  

### ISSUE THREAD

**Issue by rohinibaraskar** [neo4j-apps/neo4j-bloom#45]
How to have browser link for each search phrase separately.
so that I can visualize graph output of query whenever I click on that URL.

**Comment by GlacialBoy** [comment]
Hello @rohinibaraskar !
Considering that you have a perspective with all the search phrases defined you can use the "DeepLinks" to create different urls for different search phrases.
https://neo4j.com/docs/bloom-user-guide/current/bloom-tutorial/deep-links/ 

For example, given a search phrase "Show me a graph" the url you need to compose is:
<BloomURL>?search=Show%20me%20a%20graph&run=true

**Comment by rohinibaraskar** [comment]
Awesome its working Thank you @GlacialBoy 👍
