### ISSUE TITLE
Scene sharing without write permissions

### ISSUE THREAD

**Issue by philmcnamara** [neo4j-apps/neo4j-bloom#51]
I would like my team to be able to create and share scenes between themselves, but I can't figure out a way to allow that without full WRITE access (I do not want to permit creating, editing, or deleting nodes, which come with WRITE)

In the docs for perspectives there is a suggestion on how to grant granular permissions for the "_Bloom_Perspective_" node label, is there anything comparable for scenes?

I have also tried granting WRITE, then denying or revoking DELETE, neither seems to stop Bloom.

**Comment by yirensum** [comment]
Hey Phil, sorry for the late reply. 

There is a way to do this by granting the following permissions:

```
CREATE ROLE reader_with_scene_access_role AS COPY OF reader
GRANT CREATE ON GRAPH * NODES _Bloom_Perspective_, _Bloom_Scene_ TO reader_with_scene_access_role;
GRANT CREATE ON GRAPH * RELATIONSHIP _Bloom_HAS_SCENE_ TO reader_with_scene_access_role;
GRANT SET PROPERTY {*} ON GRAPH * NODES _Bloom_Perspective_, _Bloom_Scene_ TO reader_with_scene_access_role;
GRANT SET PROPERTY {*} ON GRAPH * RELATIONSHIP _Bloom_HAS_SCENE_ TO reader_with_scene_access_role;
```
where `reader_with_scene_access_role` is the role your team is currently assigned with.

Also note, that during scene editing, they have set it to editing mode (I've been caught out once or twice by this, so just want to give a heads up):

![image](https://user-images.githubusercontent.com/89913753/189918063-ebc77add-a5ca-43e7-b481-e091fa933a54.png)

We are planning some work on improving RBAC (role based access control) so the above workaround should no longer required in the future - but for now, hopefully this works.

**Comment by philmcnamara** [comment]
This is working for me, thank you! This will be a huge help

**Comment by ckanz** [comment]
Glad to see your issue could be resolved @philmcnamara! If you have any issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore
