### ISSUE TITLE
Visualize temporal data using a time slider

### ISSUE THREAD

**Issue by seangrant82** [neo4j-apps/neo4j-bloom#54]
**Problem:**
Currently there is no easy/low-code way inside of Bloom to visualize temporal data based on node/edge properties. For example, if my nodes have a datetime property (e.g. account_opened), I would like to visualize how my graph has evolved over time.  Also, this could allow me to see a point in time for further analysis.

**Alternative:**
Currently only way to achieve something like this would be  either through custom app (python notebook, etc) outside of Bloom or through the use of cypher queries to only retrieve portions of graph filter based on the time property (which means you would have to know ahead of time which timeframe to select)

**Enhancement:**
Propose to add a range/time slider that can look at either one property or a start/end set of properties (e.g. account_open and account_closed) to dynamically retrieve node/edges for a temporal visualization. 

_Here is an example of a complex time slider from ArcGIS_
![image](https://user-images.githubusercontent.com/11846453/191096667-2efa4538-ade2-47b7-a760-b975a7bcaa1d.png)

**Comment by adriens** [comment]
:heavy_plus_sign: :one: :ballot_box:

**Comment by GuangxueCao** [comment]
👋 Hi @seangrant82 , thanks for the feature request. This request has been added to our backlog for consideration.

**Comment by adriens** [comment]
BTW, does a metadata exist on node like on ELK where we get the node creation timestamp medatata ?

**Comment by GuangxueCao** [comment]
Hi @adriens,  I’m afraid that is not possible at the time. 

If you have control over when a node is created, you could set the creation time to a property manually.

**Comment by adriens** [comment]
Hi @GuangxueCao , thnaks a lot for your feedback, ... it totally makes sense

> If you have control over when a node is created, you could set the creation time to a property manually.

Yep, that's what we did. In fact, that would be nice to have this **as a Neo4J core feature** as a special internal field :+1:

**Comment by seangrant82** [comment]
@adriens is this what you did?: https://stackoverflow.com/questions/23440277/neo4j-cypher-query-with-timestamp#:~:text=It%20does%20not%20have%20anything%20to%20do%20with,does%20not%20store%20any%20creation%20timestamps%20by%20default.

**Comment by adriens** [comment]
@seangrant82 :

> TIMESTAMP() is a [scalar function](http://neo4j.com/docs/3.0.1/query-functions-scalar.html#functions-timestamp) to mean the exact time at query execution.

So nope, it would rather be somehting like : [`@timestamp `](https://discuss.elastic.co/t/what-is-the-difference-between-timestamp-and-timestamp/46464) : 

>  "@ fields are usually ones generated by Logstash as metadata ones, @timestamp being the value that the event was processed by Logstash."

**Comment by ckanz** [comment]
Hi @seangrant82, glad to report we implemented your suggested feature! It is called "Slicer" and you can find out more about it here: https://neo4j.com/docs/bloom-user-guide/current/bloom-tutorial/slicer/ Thank you for the great suggestion!

I will be closing this issue now, nut if you have any or suggestions or issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore
