### ISSUE TITLE
🙏 Feature Request > Export a scene to a cypher query

### ISSUE THREAD

**Issue by adriens** [neo4j-apps/neo4j-bloom#55]
# ❔  About

Bloom is an amazing discovery tool. And today at the office, while making a demo on new relationships and nodes, we wanted to share a scene we built interactively... as a code.

☝️  We finally did a screenshot as we could not find a way to export it a a `cypher` script

# 🎯 Feature request

- Be able to export an interactuvely built scene as a `cypher` script

**Comment by GlacialBoy** [comment]
Hello @adriens !!
We are very glad that Bloom helps you in your Graph exploration.

Thanks for filing a feature request, there is a feature that is not documented but it can be useful to you in this case, using a keyboard shortcut is possible to get the list of nodes that you selected in the Scene.

So given a scene like this
<img width="643" alt="Screenshot 2022-09-30 at 09 49 26" src="https://user-images.githubusercontent.com/2997749/193219526-bbbedcec-86fb-47d2-9f6b-503a833f8b34.png">

After selecting all the nodes (`⌘+a` in Mac or `Ctrl+a` in Win) if you press the "Copy" shortcut (`⌘+c` in Mac or `Ctrl+c` in Win) and paste the result in a text file (`⌘+v` in Mac or `Ctrl+v` in Win ) you will get something like

```
MATCH (a0:Film {wikiTitle: "The Matrix"})
MATCH (a5:Person {wikiTitle: "Joe Pantoliano"})
MATCH (a1:Person {wikiTitle: "Don Davis (composer)"})
MATCH (a4:Person {wikiTitle: "Gloria Foster"})
MATCH (a7:Person {wikiTitle: "Marcus Chong"})
MATCH (a2:Person {wikiTitle: "Paul Goddard (actor)"})
MATCH (a3:Person {wikiTitle: "Robert Taylor (Australian actor)"})
MATCH (a6:Person {wikiTitle: "Belinda McClory"})
return a0, a1, a2, a3, a4, a5, a6, a7
```
Which can be easily be manipulated and create other queries. 
Unfortunately the positions and other information related to the visualisation cannot be exported in the same way.

I hope this can help you in getting the most out of Bloom!

**Comment by adriens** [comment]
Hi @GlacialBoy , YES !!! This exacalty what I needed :heavy_heart_exclamation: 

Thanks a lot for your help... and yes, we really enjoy Bloom a lot.
