### ISSUE TITLE
Bloom > Unable to export to csv 

### ISSUE THREAD

**Issue by adriens** [neo4j-apps/neo4j-bloom#61]
## :grey_question: About

In Bloom I'm not able to export as `csv`... but I cannot find the button to achieve the export.

## :information_source: Environment

- Env : Neo4J Desktop
- Neo4J version : `5.11.0`
- Bloom up-to-date embedded w/ Neo4J Desktop Edition
- OS : `Linux Mint 21.2 Victoria \n \l`

## :footprints: Steps to reproduce

1. Startup database
2. Launch Bloom
3. Open/create a perspective with data
4. Right-click to Export to csv
5. Get the wozard
6. Do not find how to achieve the export
![image](https://github.com/neo4j/neo4j/assets/5235127/59f62f72-9943-4962-b305-6a0cfec74f05)

**Comment by ckanz** [comment]
Hi @adriens, thanks for reporting this.

When there are many categories and/or relationships and the Bloom window’s height is a little shorter, the “Export” and “Cancel” buttons at the bottom can be cut off. However, the entire window outside of the categories and relationship lists should be scroll-able to reach the buttons:

[Screencast from 2023-09-12 09-42-43.webm](https://github.com/neo4j-devtools/neo4j-bloom/assets/13528589/1a3fa861-197d-490e-a130-be8573da108e)

We’ve been updating the UI of the CSV export modal as part of the upcoming 2.10 release later this month which will address this.

**Comment by adriens** [comment]
Hi @ckanz , thanks a lot for the video : I'm giving it a try right now and will let you know

**Comment by adriens** [comment]
Yes, I did not see the right part :sweat_smile: 
Thanks a lot for your help :pray:
