### ISSUE TITLE
may I know is it open source?

### ISSUE THREAD

**Issue by username7171** [neo4j-apps/neo4j-bloom#68]
it is a fantastic tool to edit the graph on the browser.

**Comment by GlacialBoy** [comment]
Hello @sunset1234321 
Bloom is closed source so we are not publishing the source code anywhere.
You can still use Bloom in Neo4j Desktop and in Neo4j Aura for free!

**Comment by adriens** [comment]
Yup, it's freeware, and free to use on a local instance.
👉 neodash is open source

**Comment by ckanz** [comment]
I will be closing this issue since it's been some time since the last reply. If you have any more questions or issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore
