### ISSUE TITLE
GDS - PageRank Centrality with relationships weight crash

### ISSUE THREAD

**Issue by Mintactus** [neo4j-apps/neo4j-bloom#72]
Hi

Using
Neo4j 5.16
GraphDataScience 2.5.7
Neo4j Bloom 2.11
Google Chrome 120.0.6099.235
The computer is chromebook CP714-1WN-560E

I'm experiencing an unexpected refresh of the bloom webpage as soon as I'm trying to run the centrality pageRank algo with a relationships weight. I tried

- Private browser to exclude any cookies or tempory data isssues
- Another version of graph data science 2.5.5

**Comment by GlacialBoy** [comment]
Thanks for reporting @Mintactus , it has been solved and the fix is deployed in https://workspace-preview.neo4j.io/workspace/explore

**Comment by ckanz** [comment]
Hi @Mintactus, I will be closing this issue now that we deployed a fix. If you have any issues with Bloom, please feel free to raise a new issue here or on Canny https://neo4j-aura.canny.io/explore

Thanks again for reporting the bug!
