### ISSUE TITLE
Cannot change the color

### ISSUE THREAD

**Issue by Mintactus** [neo4j-apps/neo4j-bloom#73]
It's not possible to change the color of a relationship anymore in bloom using google chrome
121.0.6167.212

**Comment by fidalya** [comment]
Hello @Mintactus

Could you please clarify a couple of things to assist with the investigation:

- Which version of Bloom are you using and is it deployed on Aura or your local environment?
- Is the issue related to the use of rule-based styling or not?
- Any additional information that can provide more context would be helpful.

thank you

**Comment by Mintactus** [comment]
Thanks for reaching out

I'm using Bloom 2.11
Noe4j 5.16 On Google cloud VM

I tried to reproduce the issue and I was not able to do it, so i guess we
can consider it as fixed.

Maybe a recent version of chrome fixed it.

**Comment by fidalya** [comment]
Glad to hear that everything is fine now!
