### ISSUE TITLE
Can I obtain the source code for the Neo4j bloom front-end web?

### ISSUE THREAD

**Issue by suqisuqi** [neo4j-apps/neo4j-bloom#74]
I downloaded the neo4j bloom tool from the official website, and the front-end code inside is already published. I can directly run and use it on a web server. Now I want to make some modifications and customized development based on the front-end code, but what I have obtained is the published front-end code. Can I obtain the web front-end source code of Neo4j Bloom

**Comment by GlacialBoy** [comment]
Hello @suqisuqi ,
Neo4j Bloom unfortunately is not open source so the code is not available for external developers and cannot be customised. 
You can eventually integrate with an external system using iframe or [deep link](https://neo4j.com/docs/bloom-user-guide/current/bloom-tutorial/deep-links/).
