### ISSUE TITLE
Property set via CYPHER not shown in Bloom

### ISSUE THREAD

**Issue by michela** [neo4j-apps/neo4j-bloom#8]
Properties set on a node in the database via CYPHER are not showing up for that node in Bloom.

ie. this node is in db (values changed for here)
{
  "name": "XXX",
  "website": "XXX",
  "twitter": "XXX",
  "image_url": "XXX",
  "slug": "XXX",
  "facebook": "XXX"
}

node id 867 is the only one using properties "website" and "facebook"

In Browser this query returns the node in results
MATCH (n) WHERE EXISTS(n.website) RETURN n

In Bloom, searching for the node by full text search, returns the node but these two properties
 "website" and "facebook" are not shown or accessible

**Comment by jexp** [comment]
Does this node have a label too?
Labels are required on nodes to work in bloom.

**Comment by michela** [comment]
>Does this node have a label too?

No, but something else going on. I got one of the problem nodes to display all properties by re-setting them in CYPHER but still without label. While in another instance, I've just added label as per your comment but all properties still not showing.

**Comment by michela** [comment]
![property-bloom-bug](https://user-images.githubusercontent.com/99073/55679284-3bf7e880-594c-11e9-8d97-f5a19b51b816.png)

Here's an example - on left, instagram property not accessible, on right (same db) the same node has this property, label property set

Screenshot showing Neo4j enterprise v3.5.1 / Bloom 1.0.6 / Desktop 1.1.18

**Comment by tiansivive** [comment]
Hi Michela

Are you refreshing data after modifying it via Cypher in Browser? You can do that by right clicking to open the context menu and then picking the appropriate option.

If you did that already, then it could be that Bloom doesn't *hit* that node while sampling the graph to figure out which property sets relate to which labels. There is an ongoing investigation on how to deal with this sort of issue.

**Comment by michela** [comment]
Yes, definitely refreshing.

>Bloom doesn't hit that node while sampling the graph to figure out which property sets relate to which labels. There is an ongoing investigation on how to deal with this sort of issue.

Node property visibility seems to be addressed via tips above
