### ISSUE TITLE
Edit relationship property results in blank screen

### ISSUE THREAD

**Issue by michela** [neo4j-apps/neo4j-bloom#9]
Repro:
* Create relationship with properties in Neo4j browser
* Reload Bloom
* Inspect relationship with properties
* Click on EDIT icon
* Enter value

On key press in value field, window goes blank / white

**Comment by tiansivive** [comment]
This should be fixed in the next release

**Comment by michela** [comment]
ETA on next release? Bloom v1.0.6 has this issue
